additional_question_data_1 = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Albert Einstein had trouble with mathematics when he was in school.",
     "correct_answer": "False",
     "incorrect_answers": "True"},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Books",
     "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named &#039;Little Man&#039; and &#039;Fat Boy&#039;.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
     "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
     "correct_answer": "False", "incorrect_answers": "True"},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
     "correct_answer": "True", "incorrect_answers": "False"},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": "False"},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
     "incorrect_answers": "True"},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
     "correct_answer": "True", "incorrect_answers": "False"}]
